print("Hello World")
print(6)
print(5.4)
print(False)
print("Vaidehi", "Twisha", "Ami", "Prushti")
print("Vaidehi", "Twisha", "Ami", "Prushti", sep='_')
print("Vaidehi\n", "Twisha\n", "Ami\n", "Prushti\n")
print("India", 5, True)
print("Hello", end=' ' )
print("World")
